// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} className
 * @returns {Promise.<void>}
 */
export async function JavaScript_SlideToElementClass(className) {
	// BEGIN USER CODE
	let errorElems = document.getElementsByClassName(className);
    if(errorElems.length > 0){
        errorElems[0].scrollIntoView({ behavior: 'smooth'});
    }
	// END USER CODE
}
